let render ~code ~reason = 
  <div class="py-4 sm:py-12">
    <div class="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
      <h2 class="text-2xl leading-8 font-semibold font-display text-gray-900 sm:text-3xl sm:leading-9">
        Oops, an error occured!
      </h2>
      <div class="mt-0 mb-4 text-gray-600">
        <%i code %> <%s reason %>
      </div>
    </div>
  </div>

let render_debug ~debug_dump ~code ~reason = 
  <div class="py-4 sm:py-12">
    <div class="max-w-8xl mx-auto px-4 sm:px-6 lg:px-8">
      <h2 class="text-2xl leading-8 font-semibold font-display text-gray-900 sm:text-3xl sm:leading-9">
        Oops, an error occured!
      </h2>
      <div class="mt-0 mb-4 text-gray-600">
        <%i code %> <%s reason %>
      </div>
      <p>
        This error page has been generated by Dream's fallback handler. <br>
        Make sure to set the debugging mode off when deploying your application in production.
      </p>
    </div>
    
    <div class="mt-6 bg-white max-w-8xl mx-auto sm:px-6 lg:px-8">
      <div class="border-b border-t border-gray-200 sm:border sm:rounded-lg overflow-hidden">
        <div
          class="px-4 py-2 border-b border-gray-200 flex justify-between items-center bg-white sm:py-4 sm:px-6 sm:items-baseline">
          <div class="flex items-center">
            <h3 class="font-regular text-base md:text-lg leading-snug truncate">
              Debug Dump
            </h3>
          </div>
        </div>
        <div class="relative bg-gray-500">
          <div class="block">
          <pre class="block scrollbar-none m-0 p-0 overflow-auto text-white text-sm bg-gray-800 leading-normal"><code class="inline-block p-4 scrolling-touch subpixel-antialiased"><%s debug_dump %></code></pre>
          </div>
        </div>
      </div>
    </div>
  </div>